var _api_root = 'https://hx.possji.cn/admin.php/';
var api = {
  Wxapp: {
    login: _api_root + 'Wxapp/login',
    upload: _api_root + 'Wxapp/upload',
    fabu_handle: _api_root + 'Wxapp/fabuhandle',
    indexList:_api_root + 'Wxapp/indexlist',
    listview: _api_root + 'Wxapp/listview',
    tijiaohandle: _api_root + 'Wxapp/tijiaohandle',
    hudahandle: _api_root + 'Wxapp/hudahandle',
    zan: _api_root + 'Wxapp/zan',
    cai: _api_root + 'Wxapp/cai',
    more_list: _api_root + 'Wxapp/more_list',
    banners: _api_root + 'Wxapp/banner',
    shetuan: _api_root + 'Wxapp/shetuan',
    more_huda: _api_root + 'Wxapp/more_huda',
    more_shetuan: _api_root + 'Wxapp/more_shetuan',
    join_shetuan: _api_root + 'Wxapp/join_shetuan',
    st_view: _api_root + 'Wxapp/st_view',
    more_stxlist: _api_root + 'Wxapp/more_stxlist',
    userlist: _api_root + 'Wxapp/userlist',
    more_myxlist: _api_root + 'Wxapp/more_myxlist',
    userhufu: _api_root + 'Wxapp/userhufu',
    more_myhlist: _api_root + 'Wxapp/more_myhlist',
    usershetu: _api_root + 'Wxapp/usershetu',
    edit_view: _api_root + 'Wxapp/edit_view',
    tiezi_edit_handle: _api_root + 'Wxapp/tiezi_edit_handle',
    tiezidel: _api_root + 'Wxapp/tiezidel',
    seach_st: _api_root + 'Wxapp/seach_st',
    jiaru: _api_root + 'Wxapp/jiaru',
    more_myslist: _api_root + 'Wxapp/more_myslist',
    wode: _api_root + 'Wxapp/wode',
    cate: _api_root + 'Wxapp/shetuantype',
    shen: _api_root + 'Wxapp/shen',
    deletehf: _api_root + 'Wxapp/deletehuifu',
    tuituan: _api_root + 'Wxapp/tuituan',
  },
};
module.exports = api;